version: '3.1'

services:
  db:
    build: .
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: purchase_list
      MYSQL_USER: user
      MYSQL_PASSWORD: ${DOCKER_DATASOURCE_PASSWORD}
    ports:
      - 3307:3306
    volumes:
      - $PWD/sql:/docker-entrypoint-initdb.d
